# Generated by Django 4.2.6 on 2023-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=150)),
                ("course_duration", models.CharField(max_length=150)),
                ("course_fees", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=100)),
                ("stu_phno", models.BigIntegerField()),
                ("stu_email", models.CharField(max_length=150)),
                ("paid_fees", models.IntegerField()),
                ("pending_fees", models.IntegerField()),
                ("stu_course", models.CharField(max_length=150)),
            ],
        ),
    ]
