# Generated by Django 4.2.6 on 2023-11-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("StudentApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="stu_city",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="StudentApp.city",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="stu_course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="StudentApp.course",
            ),
        ),
    ]
